### ISSUE TITLE
absURL causes pages not to load from menu

### ISSUE THREAD

**Issue by TimothyRogers** [Sheffield-Digital-Twin-Hub/sheffield-digital-twin-website#2]
Under current settings absURL is not correctly assigning URLs to the menu pages when building with Hugo on Github.

This issue also affects some CSS and JS imports.

**Comment by dsbrennan** [comment]
The issue has been fixed by setting the baseURL property within the config file.
When testing locally, you may need to reset the config.toml to baseURL=""
